[package]
name = "russian-phd-thesis"
version = "0.0.1"
compiler = "0.11.0"
entrypoint = "thesis.typ"
repository = "https://github.com/SergeyGorchakov/russian-phd-thesis-template-typst"
authors = ["Sergei Gorchakov"]
license = "MIT"
description = "A russian phd thesis template"
keywords = ["thesis", "phd", "vak", "russian"]
categories = ["thesis"]

[template]
path = [".devcontainer", "common", "images", "thesis"]
entrypoint = "thesis.typ"
thumbnail = "images/thumbnail.png"